// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/c/[slug]" | "/cartao/[id]" | "/dashboard" | "/dashboard/clients" | "/dashboard/clients/[id]" | "/dashboard/clients/new" | "/dashboard/editor/[siteId]" | "/dashboard/sites" | "/login" | "/preview/[id]" | "/register" | "/s/[slug]"
type AppRouteHandlerRoutes = "/api/analyze-url" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/register" | "/api/clients" | "/api/clients/[id]" | "/api/clients/convert-lead" | "/api/deep-crawl" | "/api/scan" | "/api/share" | "/api/share/[id]" | "/api/sites" | "/api/sites/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/analyze-url": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/register": {}
  "/api/clients": {}
  "/api/clients/[id]": { "id": string; }
  "/api/clients/convert-lead": {}
  "/api/deep-crawl": {}
  "/api/scan": {}
  "/api/share": {}
  "/api/share/[id]": { "id": string; }
  "/api/sites": {}
  "/api/sites/[id]": { "id": string; }
  "/c/[slug]": { "slug": string; }
  "/cartao/[id]": { "id": string; }
  "/dashboard": {}
  "/dashboard/clients": {}
  "/dashboard/clients/[id]": { "id": string; }
  "/dashboard/clients/new": {}
  "/dashboard/editor/[siteId]": { "siteId": string; }
  "/dashboard/sites": {}
  "/login": {}
  "/preview/[id]": { "id": string; }
  "/register": {}
  "/s/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
